{% set name = "opensimplex" %}
{% set version = "0.4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opensimplex-{{ version }}.tar.gz
  sha256: 881163ba74b443c1498d43b4e6567635a57171e43174db1e41901580b859145d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy >=1.22
  run:
    - python >={{ python_min }}
    - numpy >=1.22

test:
  imports:
    - opensimplex
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/lmas/opensimplex
  summary: OpenSimplex is a noise generation function like Perlin or Simplex noise, but better.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MuellerSeb
